### ISSUE TITLE
Add Community Guidelines

### ISSUE THREAD

**Issue by shyamd** [SMTG-UCL/galore#16]
As per the JOSS Review guidelines, it would be good if you added some info on community guidelines on contribution, posting issues, and seeking support. Doesn't have to be complicated, but always good to be succinct. 

It's also a good guide to customize the issue template.

**Comment by ajjackson** [comment]
Rather than group together "community guidelines", in the pull request #17 I have added a CONTRIBUTING file with information for would-be contributors and added a separate note about support in the README.

**Comment by shyamd** [comment]
Yes, you read my cryptic comment perfectly. :) 
The PR looks great. I'll go ahead and update the review once its merged in. 

Thank!

**Comment by ajjackson** [comment]
Done!
