### ISSUE TITLE
MP API and a bug

### ISSUE THREAD

**Issue by shyuep** [SMTG-UCL/galore#28]
Thanks for the great package. I have been using it to plot XPS and I would like to suggest a few things:

1. Allow direct analysis from a CompleteDOS from the Materials Project API (this can be obtained via the pymatgen.ext.matproj.MPRester). I did try using the CompleteDOS object as an input to process_pdos (which the Documentation indicated as being supported), but I think the code logic is wrong because the code expects a string. I think analysis from a pymatgen CompleteDOS is probably the most robust way to code the whole thing because you can then get the CompleteDOS from any source, including LOBSTER (which is another feature request).
2. offset in plot_pdos does nothing as far as I can tell. This is actually needed because otherwise the binding energies are wrong.

**Comment by utf** [comment]
Thanks for the suggestions.

As a note to @ajjackson: We already have support internally for handling `CompleteDos` objects See: https://github.com/SMTG-UCL/galore/blob/01fb7e35f2537f29d296dde8c43cf1954b437690/galore/formats.py#L497

We just need to add another line in this if statement to check if the input is a `CompleteDos`. https://github.com/SMTG-UCL/galore/blob/01fb7e35f2537f29d296dde8c43cf1954b437690/galore/__init__.py#L159

**Comment by ajjackson** [comment]
Thank you @shyuep for reporting these bugs. They have now been fixed with #31 and #32 . I agree that a good interface with Pymatgen should be useful for access to other Pymatgen data sources such as LOBSTER.
