### ISSUE TITLE
How to change the font size of the labels, and stuff?

### ISSUE THREAD

**Issue by peter308** [SMTG-UCL/galore#46]
Dear developer

I would like to know in which python file shall I look so that I can change the axis size, font, and other stuff? Tks.

with kind regards,
Peter

**Comment by ajjackson** [comment]
Hi Peter,

`galore-plot-cs` has a couple of options to set font size and figure size.

Apart from that, the best way to manipulate the appearance is by creating a matplotlib style file and passing it to the `--style` parameter. There is a link in the [Galore docs](https://galore.readthedocs.io/en/latest/cli.html#style-files) to the relevant Matplotlib docs page. Sumo, Lobsterpy and Euphonic also use these stylesheets for customisation: you might find this part of the Euphonic docs useful: https://euphonic.readthedocs.io/en/stable/styling.html#using-matplotlib-styles
